import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import { FaWhatsapp, FaInstagram, FaFacebook, FaTwitter, FaYoutube } from 'react-icons/fa';
import './Footer.css';

const Footer = () => {
  return (
    <footer className="footer bg-black text-light py-4" style={{width : "100%", borderTop:"1px solid gray"}}>
      <Container className='foot_container'>
                <Col md={4} className="text-center text-md-left mb-3 mb-md-0">
                    <h5 className="mb-3">Follow Us !!</h5>
                    <div className="d-flex justify-content-center justify-content-md-start" style={{marginLeft : "100px"}}>
                        <a href="#" className="text-light mx-2"><FaWhatsapp size={24} /></a>
                        <a href="#" className="text-light mx-2"><FaInstagram size={24} /></a>
                        <a href="#" className="text-light mx-2"><FaFacebook size={24} /></a>
                        <a href="#" className="text-light mx-2"><FaTwitter size={24} /></a>
                        <a href="#" className="text-light mx-2"><FaYoutube size={24} /></a>
                    </div>
                </Col>
                <Col md={8} className="text-center text-md-left">
                    <p className="footer-text mb-1">
                    It's a limited liability company incorporated under the laws of Curacao. Players are requested not to contact any untrusted sources for its accounts as this is an online site and they can only register independently without any agents. Only deposit through the account details generated by the system or provided by our official support team.
                    </p>
                    <p className="footer-text">Rules & Regulations 2016-2024</p>
                </Col>
            
      </Container>
    </footer>
  );
};

export default Footer;
